# Numpy(넘파이)
- 수치 연산을 빠르게 할 수 있는 수치 해석을 위한 라이브러리이다.
- 배열을 표한할 수 있다.(숫자로 된 큰 배열 데이터를 다룰 때 사용된다.)

In [1]:
import numpy as np # 넘파이를 임포트하는 방법이다.

## 넘파이 배열 생성하기
- 스칼라, 벡터, 매트릭스 글에 정확한 배열 생성 방법이 나와있으니 여기서는 넘어가도록 한다.

In [2]:
# np.array()로 넘파이 배열을 생성할 수 있다.
arr = np.array([1, 2, 3])
print(arr, type(arr)) #  <class 'numpy.ndarray'>

[1 2 3] <class 'numpy.ndarray'>


## 넘파이 배열의 사칙연산

In [37]:
v1 = np.array([1, 2, 3, 4, 5])
v2 = np.array([6, 7, 8, 9, 10])

# 사칙연산
print(v1 + v2)
print(v1 - v2)
print(v1 * v2)
print(v1 / v2)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [69]:
# 브로드캐스팅
# 크기가 같은 배열은 연산이 가능하다.
# 서로 다른 모양의 배열도 일정 조건을 만족하면 연산할 수 있는 기능

# 조건
# 1.원소가 하나인 배열은 어떤 배열이나 브로드캐스팅이 가능하다
# 2.하나의 배열이 1차원의 배열인 경우 가능하다.
# 3. 차원의 짝이 맞을 때 가능하다.

arr1 = np.array([1, 2, 3]) # 1행 3열
arr2 = np.array([4, 5, 6]) # 1행 3열
arr3 = np.array([7])
arr4 = np.array([[1, 2, 3], [4, 5, 6]]) # 2행 3열
arr5 = np.array([[[0,1],[2,3],[4,5],[6,7]],[[8,9],[10,11],[12,13],[14,15]],[[16,17],[18,19],[20,21],[22,23]]])
arr6 = array2d = np.array([[0,1],[2,3],[4,5],[6,7]])

# 크기가 같으면 브로드캐스팅 없이도 계산이 가능하다.
print(arr1 + arr2)

# 원소가 하나인 배열과의 연산
# 원소가 하나인 배열은 어떤 배열과도 연산이 가능하다.
print(arr1 + arr3)
print(arr2 + arr3)
print(arr4 + arr3)

# 하나의 배열이 1차원인 경우
# 하나의 배열이 1차원인 경우도 연산이 가능하다.
print(arr1.ndim) # arr1은 1차원
print(arr2.ndim) # arr2은 1차원
print(arr4.ndim) # arr4는 2차원

print(arr1 + arr4) # arr1이 1차원이므로 2차원 배열과의 연산이 가능하다/
print(arr2 + arr4)

# 차원의 짝이 맞는 경우
print(arr5.shape) # (3, 4, 2)
print(arr6.shape) # (4, 2)
print(arr5 + arr6)

[5 7 9]
[ 8  9 10]
[11 12 13]
[[ 8  9 10]
 [11 12 13]]
1
1
2
[[2 4 6]
 [5 7 9]]
[[ 5  7  9]
 [ 8 10 12]]
(3, 4, 2)
(4, 2)
[[[ 0  2]
  [ 4  6]
  [ 8 10]
  [12 14]]

 [[ 8 10]
  [12 14]
  [16 18]
  [20 22]]

 [[16 18]
  [20 22]
  [24 26]
  [28 30]]]


In [63]:
# 행과 열을 서로 바꾸는 방법 : np.transpose
arr = np.array([[1], [2], [3]])
print(arr) # 3행 1열

print(np.transpose(arr)) # 1행 3열

[[1]
 [2]
 [3]]
[[1 2 3]]


## 넘파이에서 사용할 수 있는 것들

In [3]:
# 배열의 크기 구하기 : .shape
print(arr, arr.shape) # 크기가 3이다.

[1 2 3] (3,)


In [4]:
# 배열의 차원 구하기 : .ndim
print(arr, arr.ndim) # 1차원이다.

[1 2 3] 1


In [5]:
# 배열의 요소 개수 구하기 : .size
print(arr, arr.size) # 요소의 개수가 3개이다.

[1 2 3] 3


In [7]:
# 배열 요소의 타입 구하기 : .dtype
print(arr, arr.dtype) # int32 => 정수형데이터로 이루어져있다.

# type()과의 차이점
print(arr, type(arr)) # <class 'numpy.ndarray'> => type()은 배열의 각 요소가 아닌 배열이 넘파이 배열임을 알려준다.

[1 2 3] int32
[1 2 3] <class 'numpy.ndarray'>


In [21]:
# 벡터와 매트릭스의 인덱싱과 슬라이싱

v = np.array([1, 2, 3, 4, 5]) # 벡터 생성
m = np.array([[10, 20], [30, 40]]) # 매트릭스 생성

# 벡터 인덱싱
print(v[0]) # 리스트와 동일한 방법으로 해줄 수 있다.
print(v[1])
print(v[2])
print(v[3])
print(v[4])

# 벡터의 슬라이싱
print(v[0:3]) # 슬라이싱도 리스트와 동일한 방법으로 해줄 수 있다.

# 매트릭스의 인덱싱
print(m[0][0]) # 행과 열을 지정하여 인덱싱을 해줄 수 있다.
print(m[0][1])
print(m[1][0])
print(m[1][1])

# 매트릭스의 슬라이싱
print(m[0,1]) # 리스트와는 다르게 콤마로 구분한다.

1
2
3
4
5
[1 2 3]
10
20
30
40
20


In [46]:
# 0으로 이루어진 배열 생성 : np.zeros()
m = np.zeros((3, 4)) # 3X4크기의 0으로 이루어진 배열 생성
print(m)

# 1로 이루어진 배열 생성 : np.ones()
m = np.ones((3, 4)) # 3X4크기의 1로 이루어진 배열 생성
print(m)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 넘파이 배열의 추가, 수정, 삭제

In [30]:
m1 = np.array([[1, 2, 3]])
m2 = np.array([[4, 5, 6]])
print(m1)

# 추가 => .append
np.append(m1, m2, axis = 0) # axis = 0 : axis는 축을 의미하며 0은 행, 1은 열을 의미한다.
print(m2) # 할당해주지 않으면 추가를 해줘도 배열이 변하지 않는다.

m1 = np.append(m1, m2, axis = 0)
print(m1)

m1 = np.append(m1, [[7], [8]], axis = 1) # 열로 추가
print(m1)

[[1 2 3]]
[[4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3 7]
 [4 5 6 8]]


In [36]:
# 삭제 -> .delete(배열, 인덱스. 축)
m1 = np.array([[1, 2, 3], [4, 5, 6]])
print(m1)

m1 = np.delete(m1, 0, axis = 1) # 첫번째 열 삭제
print(m1)

m1 = np.delete(m1, 1, axis = 0) # 첫번째 행 삭제
print(m1)

[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]
[[2 3]]


In [43]:
# 수정
v1 = np.array([1, 2, 3])
m1 = np.array([[1, 2, 3], [4, 5, 6]])
print(v1)
print(m1)

# 벡터(1차원) 수정
v1[0] = 30 # 인덱스를 지정하고 값을 수정할 수 있다.
print(v1)

# 매트릭스(2차원) 수정
m1[1][1] = '20' # 행과 열의 인덱스를 지정하고 값을 수정할 수 있다.
print(m1)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[30  2  3]
[[ 1  2  3]
 [ 4 20  6]]


In [52]:
# 형변환
arr = np.array([1, 2, 3, 4, 5])
print(arr)

# 정수 배열을 실수형으로 형변환 => .astype()
arr = arr.astype(float)
print(arr, arr.dtype) # float64 실수형으로 형변환이 되었다.

[1 2 3 4 5]
[1. 2. 3. 4. 5.] float64
