# 스칼라
- 텐서가 0차원이고, 축이 없다.
- 양의 실수, 음의 실수, 정수인 값이 하나만 존재한다
- 크기만 가지고 있다

In [2]:
import numpy as np # 스칼라를 만들려면 넘파이가 필요하다.

In [3]:
# np.array() : 넘파이 배열을 만들 수 있다.
a = np.array(21) # 이렇게 값이 하나만 들어가게 되면 스칼라가 만들어진다
print(a, type(a)) # a의 타입은 넘파이 배열로 만들어진다.

21 <class 'numpy.ndarray'>


In [4]:
# 스칼라의 차원 확인 => .ndim : 넘파이 배열의 차원을 확인할 수 있다.
print(a.ndim) # 0차원으로 나오므로 a는 스칼라이다.

0


In [5]:
# 스칼라의 크기 확인 => .shape : 넘파이 배열의 크기를 확인할 수 있다.
print(a.shape) # ()의 뜻은 축이 없다는 뜻이다.

()


# 벡터
- 텐서가 1차원이고 하나의 축을 가지고 있다.
- 하나의 행 또는 열로 구성된 데이터의 집합이다.
- 각 요소는 스칼라 값으로 구성되어 있다.
- 벡터의 각 요소는 크기와 방향을 가질 수 있다.
- 공간의 점, 힘, 속도, 가속도 등과 같은 물리적인 개념을 나타낸다.

In [7]:
v1 = np.array([10]) # 스칼라의 생성과는 다르게 대괄호로 감싸준다. (하나의 값이라도 대괄호에 감싸져 있다면 벡터이다.)
print(v, type(v))

# 차원 확인
print(v1.ndim) # 1차원

# 크기 확인
print(v1.shape) # 차원과 형상을 가지고 있다.

[10] <class 'numpy.ndarray'>
1
(1,)


In [8]:
v2 = np.array([1, 2, 3, 4, 5]) # 스칼라와는 다르게 여러 값이 들어갈 수 있ㄷ다.
print(v2, type(v2))

# 차원 확인
print(v2.ndim) # 1차원

# 크기 확인
print(v2.shape) # 차원과 형상을 가지고 있다.

[1 2 3 4 5] <class 'numpy.ndarray'>
1
(5,)


In [11]:
# 범위를 정해서 벡터 생성하기
print(list(range(10))) # range함수를 통해서 범위를 정해 리스트를 생성할 수 있다.

# 벡터도 범위를 정해서 생성할 수 있는데 이 때는 np.arange()가 사용된다.
# range()함수와 동일하게 시작값, 종료값, 스텝값이 들어간다.
# 스텝값에는 실수도 들어갈 수 있다.

v3 = np.arange(0, 10, 0.5) 
print(v3, v3.dtype) # .dtype : 배열 요소의 자료형을 알려주는 함수이다.
# float64 => 배열의 각 요소가 실수로 이루어져 있다는 것을 알 수 있다.

v4 = np.arange(10)
print(v4, v4.dtype)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5] float64
[0 1 2 3 4 5 6 7 8 9] int32


In [19]:
# 벡터의 노름 구하기
# 노름 : 벡터의 길이 또는 크기

# 벡터의 노름은 피타고라스의 정리를 이용하여 구해줄 수 있다.
# 피타고라스의 정리 : 직각삼각형일 때 (빗변의 길이)^2 = (밑변의 길이)^2 + (높이)^2

v5 = np.arange(3,5)
print(v5)

# 노름 구하기(1) => 원리
v_p = np.power(v5, 2) # 배열의 각 요소에 제곱을 해준다.
print(v_p)

v_r = np.sqrt(np.sum(v_p)) # 제곱해준 배열의 각 요소의 합에 제곱근을 구해준다.
print(v_r) # norm

# 노름 구하기(hypot()함수 사용) => 위 방법에 있는 코드를 뭉친거다.
print(np.hypot(v5[0], v5[1])) # 

# 노름 구하기(np.linalg모듈 안에 있는 norm()이용)
print(np.linalg.norm(v5))

[3 4]
[ 9 16]
5.0
5.0
5.0


# 매트릭스
- 2차원인 2개의 축을 가진 행렬이다
- 행과 열이 있는 2차원 배열 형태의 데이터 구조이다
- 각 원소는 스칼라 값이며, 매트릭스의 크기는 행과 열의 수로 정의된다
- 데이터를 구조화하고 다룰 때 사용된다

In [25]:
m1 = np.array([[10, 20], [30, 40]]) # 대괄호 안에 대괄호를 사용하여 만들어줘야 한다.
print(m1, type(m1))
print(m1.dtype) # 정수형으로 이루어진 매트릭스
print(m1.shape) # 크기가 2이다.
print(m1.ndim) # 2차원

m2 = np.array([[10], [20]])
print(m2)

[[10 20]
 [30 40]] <class 'numpy.ndarray'>
int32
(2, 2)
2
[[10]
 [20]]
