# 넘파이(Numpy)
- Numeric Python의 약자로 대규모 행렬, 배열 연산에 필요한 함수나 메서드들을 제공한다.
- 특히 요즘 유행인 AI분야에서 널리 사용되고 있다.

## 넘파이 설치 방법
- 아나콘다를 사용한다면 따로 설치할 필요는 없다.
- 만약 넘파이가 깔려있지 않다면 아래 코드로 설치할 수 있다.

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


## 넘파이 Import 하는 방법
- import numpy as np로 Import할 수 있다.
- numpy는 길기 때문에 보통 np로 줄여서 사용한다.
- Import 시 as를 사용해서 별칭을 정해줄 수 있다.

In [ ]:
import numpy as np

# 넘파이 사용 방법

## 기본적인 배열 생성 및 정보 확인
- np.array를 통해 배열은 생성할 수 있다.
- 여러 차원의 배열로 생성할 수 있으며 shape 속성을 통해 크기를 확인할 수 있다.

In [8]:
import numpy as np

arr1 = np.array(['트레이서', '겐지', '위도우메이커'])
arr2 = np.array([['트레이서', '겐지'], ['아리', '야스오']])
arr3 = np.array([[['트레이서', '겐지'], ['정크렛', '리퍼']], [['아리', '야스오'], ['요네', '말파이트']]])

print(arr1, arr1.shape)
print() # 줄바꿈
print(arr2, arr2.shape)
print() # 줄바꿈
print(arr3, arr3.shape)

['트레이서' '겐지' '위도우메이커'] (3,)

[['트레이서' '겐지']
 ['아리' '야스오']] (2, 2)

[[['트레이서' '겐지']
  ['정크렛' '리퍼']]

 [['아리' '야스오']
  ['요네' '말파이트']]] (2, 2, 2)


In [11]:
# 0으로만 이루어진 배열 생성
arr = np.zeros(10)
print(arr, arr.shape, arr.dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] (10,) float64


In [12]:
# 1로만 이루어진 배열 생성
arr = np.ones(10)
print(arr, arr.shape, arr.dtype)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] (10,) float64


In [13]:
# range함수에 대응되는 arange함수
arr = np.arange(10)
print(arr, arr.shape, arr.dtype)

[0 1 2 3 4 5 6 7 8 9] (10,) int32


In [16]:
# 배열의 여러가지 정보 확인
arr = np.arange(10)
print(arr) # 배열 출력
print(arr.shape) # 배열의 크기 출력
print(arr.dtype) # 배열의 자료형 확인
print(arr.ndim) # 배열의 차원 확인

[0 1 2 3 4 5 6 7 8 9]
(10,)
int32
1


## 배열의 자료형 및 크기
- 배열의 자료형을 확인하고 변경할 수 있다.
- 배열의 크기를 변경할 수 있다.

In [18]:
# 배열 생성
arr = np.arange(10)
print(arr, arr.dtype)

[0 1 2 3 4 5 6 7 8 9] int32


In [19]:
# astype을 사용해서 배열 원소의 자료형을 변경할 수 있다.
arr_float = arr.astype(np.float64)
print(arr_float, arr_float.dtype)

# 주요 자료형
# int32, int64
# float32, float64
# bool
# object
# string_

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64


In [22]:
# 배열 크기 변경하기
# reshape(행, 열)로 변경할 수 있다.
arr_reshape = arr.reshape(2, 5)
print(arr_reshape, arr_reshape.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5)


## 배열의 연산
- 기본적인 행렬의 연산은 모두 지원한다.
- 브로드캐스팅이라는 기능이 있어 다른 크기의 배열도 연산이 가능하다.
- Transpose가 가능하다.

In [24]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("----배열 출력----")
print(arr)
print("----배열의 덧셈----")
print(arr + arr)
print("----배열의 뺄셈----")
print(arr - arr)
print("----배열의 곱셈----")
print(arr * arr)
print("----배열의 나눗셈----")
print(arr / arr)
print("----배열의 몫 연산----")
print(arr // arr)
print("----배열의 나머지 연산----")
print(arr % arr)

----배열 출력----
[[1 2 3]
 [4 5 6]]
----배열의 덧셈----
[[ 2  4  6]
 [ 8 10 12]]
----배열의 뺄셈----
[[0 0 0]
 [0 0 0]]
----배열의 곱셈----
[[ 1  4  9]
 [16 25 36]]
----배열의 나눗셈----
[[1. 1. 1.]
 [1. 1. 1.]]
----배열의 몫 연산----
[[1 1 1]
 [1 1 1]]
----배열의 나머지 연산----
[[0 0 0]
 [0 0 0]]


### 브로드 캐스팅이 되는 경우
- 둘 중 하나의 배열이 1차원일 경우
- 두 배열의 짝이 맞을 경우(첫 번째 배열의 열, 두 번째 배열의 행이 동일)
- 두 배열이 뒤에서 부터 대응하는 축의 크기가 동일하거나, 1이어야만 한다.

In [31]:
# 브로드 캐스팅

# 첫 번째 경우
arr1 = np.arange(10).reshape(2, 5)
scalar = 3
print("----둘 중 하나의 배열이 1차원----")
print(arr1 * scalar)
print()

# 두 번째 경우
arr1 = np.arange(4).reshape(4, 1)
arr2 = np.arange(4).reshape(1, 4)
print("----두 배열의 짝이 맞을 경우----")
print(arr1 * arr2)
print()

# 세 번째 경우
arr1 = np.arange(15).reshape(3, 1, 5)
arr2 = np.arange(20).reshape(   4, 5)
print("----두 배열이 뒤에서 부터 대응하는 축의 크기가 동일하거나, 1인 경우")
print(arr1 * arr2)

----둘 중 하나의 배열이 1차원----
[[ 0  3  6  9 12]
 [15 18 21 24 27]]

----두 배열의 짝이 맞을 경우----
[[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]
 [0 3 6 9]]

----두 배열이 뒤에서 부터 대응하는 축의 크기가 동일하거나, 1인 경우
[[[  0   1   4   9  16]
  [  0   6  14  24  36]
  [  0  11  24  39  56]
  [  0  16  34  54  76]]

 [[  0   6  14  24  36]
  [ 25  36  49  64  81]
  [ 50  66  84 104 126]
  [ 75  96 119 144 171]]

 [[  0  11  24  39  56]
  [ 50  66  84 104 126]
  [100 121 144 169 196]
  [150 176 204 234 266]]]


In [32]:
# Transpose
arr = np.arange(10).reshape(2, 5)
print("----원래 배열----")
print(arr)
print()

print("----Transpose한 배열")
print(arr.transpose())

----원래 배열----
[[0 1 2 3 4]
 [5 6 7 8 9]]

----Transpose한 배열
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
