# 넘파이의 범용함수
- 넘파이에서 많이 쓰이는 함수이다.
- 보통 수치 계산에 대한 함수들이 많다.

In [1]:
import numpy as np

## 절대값 계산
- np.abs함수는 절대값 계산 결과를 정수로 반환한다.
- np.fabs함수는 절대값 계산 결과를 실수로 반환한다.

In [21]:
arr_int = np.arange(-10, 0)
print(arr_int, end = '\n\n')

print("----np.abs함수 결과----")
print(np.abs(arr_int))
print("----np.fabs함수 결과----")
print(np.fabs(arr_int))

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1]

----np.abs함수 결과----
[10  9  8  7  6  5  4  3  2  1]
----np.fabs함수 결과----
[10.  9.  8.  7.  6.  5.  4.  3.  2.  1.]


## 제곱근 계산(루트)
- np.sqrt함수로 가능하다.
- ** 0.5와 같은 기능을 한다.

In [23]:
arr = np.arange(10)
print(arr, end = '\n\n')

print(np.sqrt(arr))

[0 1 2 3 4 5 6 7 8 9]

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


## 제곱 계산
- np.square함수로 가능하다.
- ** 2와 같은 기능을 한다.

In [24]:
arr = np.arange(10)
print(arr, end = '\n\n')

print(np.square(arr))

[0 1 2 3 4 5 6 7 8 9]

[ 0  1  4  9 16 25 36 49 64 81]


## e^x 계산
- np.exp함수로 가능하다.

In [25]:
arr = np.arange(10)
print(arr, end = '\n\n')

print(np.exp(arr))

[0 1 2 3 4 5 6 7 8 9]

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


## 로그 계산
- np.log함수로 가능하다.
- np.log : 밑이 e인 자연로그
- np.log10 : 밑이 10인 상용로그
- np.log2 : 밑이 2인 로그

In [28]:
arr = np.arange(2, 10)
print(arr, end = '\n\n')

print("----자연로그----")
print(np.log(arr), end = '\n\n')
print("----상용로그----")
print(np.log10(arr), end = '\n\n')
print("----밑이 2인 로그----")
print(np.log2(arr))

[2 3 4 5 6 7 8 9]

----자연로그----
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947 1.94591015
 2.07944154 2.19722458]

----상용로그----
[0.30103    0.47712125 0.60205999 0.69897    0.77815125 0.84509804
 0.90308999 0.95424251]

----밑이 2인 로그----
[1.         1.5849625  2.         2.32192809 2.5849625  2.80735492
 3.         3.169925  ]


## 부호 계산
- np.sign함수로 가능하다.
- 1은 양수 0은 0, -1은 음수를 뜻한다.

In [30]:
arr = np.arange(-5, 6)
print(arr, end = '\n\n')

print(np.sign(arr))

[-5 -4 -3 -2 -1  0  1  2  3  4  5]

[-1 -1 -1 -1 -1  0  1  1  1  1  1]


## 천장 함수와 바닥 함수
- 성분보다 크거나 같은 정수 중 가장 작은 정수(천장함수) : np.ceil함수
- 성분보다 작거나 같은 정수 중 가장 큰 정수(바닥함수) : np.floor함수

In [34]:
arr = np.arange(0,15,1.5)
print(arr, end = '\n\n')

# 천장함수
print("----천장함수----")
print(np.ceil(arr), end = '\n\n')

# 바닥함수
print('----바닥함수----')
print(np.floor(arr), end = '\n\n')

[ 0.   1.5  3.   4.5  6.   7.5  9.  10.5 12.  13.5]

----천장함수----
[ 0.  2.  3.  5.  6.  8.  9. 11. 12. 14.]

----바닥함수----
[ 0.  1.  3.  4.  6.  7.  9. 10. 12. 13.]



## 더하기 함수
- 두 배열을 더하는 함수이다.
- np.add()함수로 더할 수 있다.

In [38]:
arr1 = np.arange(8).reshape(4, 2)
arr2 = np.arange(0,0.8,0.1).reshape(4,2)

print(np.add(arr1, arr2))

[[0.  1.1]
 [2.2 3.3]
 [4.4 5.5]
 [6.6 7.7]]


## 빼기 함수
- 두 배열을 빼는 함수이다.
- np.subtract()함수로 뺄 수 있다.

In [39]:
arr1 = np.arange(8).reshape(4, 2)
arr2 = np.arange(0,0.8,0.1).reshape(4,2)

print(np.subtract(arr1, arr2))

[[0.  0.9]
 [1.8 2.7]
 [3.6 4.5]
 [5.4 6.3]]


## 곱하기 함수
- 두 배열을 곱하는 함수이다.
- np.multyply()함수로 곱할 수 있다.

In [40]:
arr1 = np.arange(8).reshape(4, 2)
arr2 = np.arange(0,0.8,0.1).reshape(4,2)

print(np.multiply(arr1, arr2))

[[0.  0.1]
 [0.4 0.9]
 [1.6 2.5]
 [3.6 4.9]]


## 나누기 함수
- 두 배열을 나누는 함수이다.
- np.divide()함수로 나눌 수 있다.

In [42]:
arr1 = np.arange(1,9).reshape(4, 2)
arr2 = np.arange(0.1,0.9,0.1).reshape(4,2)

print(np.divide(arr1, arr2))

[[10. 10.]
 [10. 10.]
 [10. 10.]
 [10. 10.]]


## 최댓값 함수
- 두 배열의 같은 위치에서의 최댓값을 반환한다.
- np.maximum()함수로 가능하다.

In [44]:
arr1 = np.arange(1,17, 2)
arr2 = np.arange(5,13)

print(np.maximum(arr1, arr2))

[ 5  6  7  8  9 11 13 15]


## 최솟값 함수
- 두 배열의 같은 위치에서의 최솟값을 반환한다.
- np.minimum()함수로 가능하다.

In [45]:
arr1 = np.arange(1,17, 2)
arr2 = np.arange(5,13)

print(np.minimum(arr1, arr2))

[ 1  3  5  7  9 10 11 12]


## 랜덤 함수
- 랜덤 함수를 사용해 배열을 생성하는 방법이다.

### np.random.normal()
- 정규 분포에서 임의의 수를 추출하여 이를 바탕으로 랜덤 배열을 생성한다.

In [48]:
arr = np.random.normal(0, 1, 10) # (정규분포의 평균, 정규분포의 표준편차, 추출할 수)
print(arr)

[-0.62190283  0.03116316  0.89834031  1.40196744  0.56575691 -0.85974547
  3.37674733  1.39107985  1.91868201  0.82884939]


### np.random.randn()
- 평균이 0, 표준편차가 1인 표준정규분포표에서 수를 추출해 배열을 생성한다.

In [49]:
arr = np.random.randn(10)
print(arr)

[-0.56515684  0.30622179 -0.08830808  0.33557999  1.09082326 -0.3253069
  0.09057086  0.58530478  0.07138265  0.07083533]


### np.random.rand()
- [0,1)범위에서 균등하게 추출한다.

In [50]:
arr = np.random.rand(2, 10)
print(arr)

[[0.39435076 0.3236273  0.69100379 0.68837446 0.99216702 0.48559246
  0.91181675 0.95573831 0.80552395 0.37353075]
 [0.30252426 0.83164031 0.25326584 0.69618558 0.39409298 0.02812303
  0.19568716 0.77921408 0.55549302 0.07920048]]


### np.random.randint()
- 정해진 범위 내에서 임의의 정수를 추출해 배열을 생성한다.

In [51]:
arr = np.random.randint(1, 10, 10)
print(arr)

[5 7 2 8 7 4 7 4 8 3]


### np.random.seed()
- 사실 랜덤함수는 랜덤이 아니다.
- 정해진 시드마다 정해진 값을 출력해준다.
- 시드를 고정하여 값을 고정할 수 있다.

In [55]:
np.random.seed(47)
arr = np.random.randint(1, 10, 10)
print(arr)

# 시드값 변경
np.random.seed(50)
arr = np.random.randint(1, 10, 10)
print(arr)

# 시드값 복구
np.random.seed(47)
arr = np.random.randint(1, 10, 10)
print(arr)

[8 7 8 9 9 4 1 8 1 8]
[1 1 2 5 7 6 7 7 6 3]
[8 7 8 9 9 4 1 8 1 8]
